/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IVaultManagerInterface extends ethers.utils.Interface {
  functions: {
    "getCDPConfig(address)": FunctionFragment;
    "getCDecimal(address)": FunctionFragment;
    "getLFR(address)": FunctionFragment;
    "getMCR(address)": FunctionFragment;
    "getSFR(address)": FunctionFragment;
    "getVault(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getCDPConfig",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getCDecimal", values: [string]): string;
  encodeFunctionData(functionFragment: "getLFR", values: [string]): string;
  encodeFunctionData(functionFragment: "getMCR", values: [string]): string;
  encodeFunctionData(functionFragment: "getSFR", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCDPConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCDecimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLFR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMCR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSFR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;

  events: {};
}

export class IVaultManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IVaultManagerInterface;

  functions: {
    getCDPConfig(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;

    getCDecimal(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLFR(collateral: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getMCR(collateral: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getSFR(collateral: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getVault(
      vaultId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getCDPConfig(
    collateral: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;

  getCDecimal(
    collateral: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

  getMCR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

  getSFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

  getVault(vaultId_: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getCDPConfig(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber]>;

    getCDecimal(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getMCR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getVault(
      vaultId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getCDPConfig(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCDecimal(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getMCR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getSFR(collateral: string, overrides?: CallOverrides): Promise<BigNumber>;

    getVault(
      vaultId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCDPConfig(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCDecimal(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLFR(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMCR(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSFR(
      collateral: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVault(
      vaultId_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
